CREATE TABLE IF NOT EXISTS `remote_app_updates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `platform` varchar(32) NOT NULL DEFAULT '' COMMENT '适用平台：android/windows/macos/ios/all',
  `channel` varchar(32) NOT NULL DEFAULT 'stable' COMMENT '发布通道：stable/beta',
  `version` varchar(64) NOT NULL DEFAULT '' COMMENT '版本号，例如 1.2.0',
  `build_number` varchar(64) NOT NULL DEFAULT '' COMMENT '构建号',
  `minimum_version` varchar(64) NOT NULL DEFAULT '' COMMENT '最低可用版本，低于该版本应强制更新',
  `release_notes` text COMMENT '更新说明',
  `update_type` varchar(32) NOT NULL DEFAULT 'link' COMMENT '更新方式：link/file/app_store',
  `download_url` varchar(1000) NOT NULL DEFAULT '' COMMENT '下载链接或 DMG 文件地址',
  `app_store_url` varchar(1000) NOT NULL DEFAULT '' COMMENT 'iOS App Store 链接',
  `package_file_id` bigint unsigned DEFAULT NULL COMMENT '关联上传文件ID，可为空',
  `package_file_name` varchar(191) NOT NULL DEFAULT '' COMMENT '上传文件名',
  `package_file_size` bigint NOT NULL DEFAULT 0 COMMENT '上传文件大小',
  `package_sha256` varchar(128) NOT NULL DEFAULT '' COMMENT '安装包 SHA256',
  `force_update` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否强制更新',
  `published` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否发布',
  `released_at` datetime(3) DEFAULT NULL COMMENT '发布时间',
  PRIMARY KEY (`id`),
  KEY `idx_remote_app_updates_lookup` (`platform`, `channel`, `published`),
  KEY `idx_remote_app_updates_released_at` (`released_at`),
  KEY `idx_remote_app_updates_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='远程 App 在线更新版本表';
