import { hostname } from "node:os";
import { execFileSync } from "node:child_process";
import { createHash, createPrivateKey, generateKeyPairSync, randomUUID, sign } from "node:crypto";
import {
  localDeviceIdentitySchema,
  summarizeDeviceIdentity,
  type DeviceSummary,
  type LocalDeviceIdentity
} from "../../shared/account.js";
import { CredentialStore } from "../security/credentialStore.js";

const identityKey = "remote.device.identity";
const privateKeyKey = "remote.device.private-key";
const deviceCodeKey = "remote.device.code";

export class DeviceIdentityStore {
  constructor(private readonly credentials = new CredentialStore("device")) {}

  async loadIdentity(): Promise<LocalDeviceIdentity | null> {
    const raw = await this.credentials.readSecret(identityKey);
    if (!raw) {
      return null;
    }
    return localDeviceIdentitySchema.parse(JSON.parse(raw));
  }

  async loadOrCreateIdentity(deviceName = defaultDeviceName()): Promise<LocalDeviceIdentity> {
    const existing = await this.loadIdentity();
    if (existing) {
      return existing;
    }

    const keyPair = generateKeyPairSync("ed25519", {
      publicKeyEncoding: { type: "spki", format: "der" },
      privateKeyEncoding: { type: "pkcs8", format: "der" }
    });
    const identity = localDeviceIdentitySchema.parse({
      deviceUID: stableDeviceUID(),
      deviceID: null,
      deviceName,
      devicePublicKey: keyPair.publicKey.toString("base64"),
      keyAlgorithm: "ed25519"
    });

    await this.credentials.writeSecret(privateKeyKey, keyPair.privateKey.toString("base64"));
    await this.saveIdentity(identity);
    return identity;
  }

  async saveIdentity(identity: LocalDeviceIdentity): Promise<void> {
    await this.credentials.writeSecret(identityKey, JSON.stringify(localDeviceIdentitySchema.parse(identity)));
  }

  async updateDeviceID(deviceID: number): Promise<DeviceSummary> {
    const identity = await this.loadOrCreateIdentity();
    const nextIdentity = localDeviceIdentitySchema.parse({ ...identity, deviceID });
    await this.saveIdentity(nextIdentity);
    return this.summary();
  }

  async updateDeviceName(deviceName: string): Promise<DeviceSummary> {
    const identity = await this.loadOrCreateIdentity();
    const nextIdentity = localDeviceIdentitySchema.parse({ ...identity, deviceName: deviceName.trim() || defaultDeviceName() });
    await this.saveIdentity(nextIdentity);
    return this.summary();
  }

  async saveDeviceCode(deviceCode: string): Promise<void> {
    const normalized = deviceCode.trim();
    if (!normalized) {
      await this.deleteDeviceCode();
      return;
    }
    await this.credentials.writeSecret(deviceCodeKey, normalized);
  }

  async loadDeviceCode(): Promise<string | null> {
    return this.credentials.readSecret(deviceCodeKey);
  }

  async deleteDeviceCode(): Promise<void> {
    await this.credentials.deleteSecret(deviceCodeKey);
  }

  async clearProvisionedDevice(): Promise<DeviceSummary> {
    const identity = await this.loadOrCreateIdentity();
    // 解绑后仍按硬件指纹复用同一标识：同一台 PC 始终对应同一个 deviceUID，
    // 重新登记时后端会更新原设备而不是新增设备。
    const nextIdentity = localDeviceIdentitySchema.parse({
      ...identity,
      deviceUID: stableDeviceUID(),
      deviceID: null
    });
    await this.saveIdentity(nextIdentity);
    await this.deleteDeviceCode();
    return this.summary();
  }

  async signNonce(nonce: string): Promise<string> {
    const rawPrivateKey = await this.credentials.readSecret(privateKeyKey);
    if (!rawPrivateKey) {
      await this.loadOrCreateIdentity();
      return this.signNonce(nonce);
    }
    const privateKey = createPrivateKey({
      key: Buffer.from(rawPrivateKey, "base64"),
      format: "der",
      type: "pkcs8"
    });
    return sign(null, Buffer.from(nonce, "utf8"), privateKey).toString("base64");
  }

  async summary(): Promise<DeviceSummary> {
    const identity = await this.loadOrCreateIdentity();
    const hasDeviceCode = Boolean(await this.loadDeviceCode());
    return summarizeDeviceIdentity(identity, hasDeviceCode);
  }

  async syncDeviceNameWithHost(): Promise<LocalDeviceIdentity> {
    const identity = await this.loadOrCreateIdentity();
    const nextName = defaultDeviceName();
    if (!isAutoGeneratedDeviceName(identity.deviceName) || identity.deviceName === nextName) {
      return identity;
    }
    const nextIdentity = localDeviceIdentitySchema.parse({ ...identity, deviceName: nextName });
    await this.saveIdentity(nextIdentity);
    return nextIdentity;
  }
}

// stableDeviceUID 基于设备硬件指纹生成稳定标识，保证同一台物理机在应用
// 重装/升级、凭据存储被清空后仍得到相同的 deviceUID，从而避免在后端反复
// 生成新的“幽灵设备”。读取硬件信息失败时回退到随机 UUID，保证可用性。
function stableDeviceUID(): string {
  const fingerprint = readHardwareFingerprint();
  if (fingerprint) {
    const hash = createHash("sha256").update(fingerprint).digest("hex");
    return `windows-${hash.slice(0, 32)}`;
  }
  return randomUUID();
}

// readHardwareFingerprint 读取 Windows 的 MachineGuid（位于注册表
// HKLM\SOFTWARE\Microsoft\Cryptography），它在系统重装前保持不变，是
// 最稳定的单机标识来源。非 Windows 平台或读取失败时返回 null。
function readHardwareFingerprint(): string | null {
  if (process.platform !== "win32") {
    return null;
  }
  try {
    const output = execFileSync(
      "reg",
      ["query", "HKLM\\SOFTWARE\\Microsoft\\Cryptography", "/v", "MachineGuid", "/reg:64"],
      { encoding: "utf8", timeout: 4000, windowsHide: true }
    );
    const match = output.match(/MachineGuid\s+REG_SZ\s+([0-9a-fA-F-]+)/);
    const guid = match?.[1]?.trim().toLowerCase();
    if (guid) {
      return `win:machine-guid:${guid}`;
    }
  } catch {
    return null;
  }
  return null;
}

export function defaultDeviceName(): string {
  if (process.platform === "win32") {
    const computerName = process.env.COMPUTERNAME?.trim();
    if (computerName) {
      return computerName;
    }
  }
  const rawHost = hostname().trim();
  const shortHost = rawHost.replace(/\.local$/i, "").trim();
  if (shortHost) {
    return shortHost;
  }
  return process.platform === "win32" ? "Codevoke Windows" : "Codevoke Desktop";
}

function isAutoGeneratedDeviceName(name: string): boolean {
  const trimmed = name.trim();
  if (!trimmed) {
    return true;
  }
  const rawHost = hostname().trim();
  const shortHost = rawHost.replace(/\.local$/i, "");
  const computerName = process.env.COMPUTERNAME?.trim();
  const candidates = new Set(
    [rawHost, shortHost, `${shortHost}.local`, computerName, defaultDeviceName()]
      .filter((value): value is string => Boolean(value?.trim()))
  );
  return candidates.has(trimmed) || trimmed.endsWith(".local");
}
