import service from '@/utils/request'

const post = (url, data) => service({ url, method: 'post', data })

export const listRemoteUsers = (data) => post('/remote-admin/users/list', data)
export const saveRemoteUser = (data) => post('/remote-admin/users/save', data)
export const updateRemoteUserStatus = (data) => post('/remote-admin/users/status', data)
export const kickRemoteUser = (data) => post('/remote-admin/users/kick', data)
export const banRemoteUser = (data) => post('/remote-admin/users/ban', data)
export const deleteRemoteUser = (data) => post('/remote-admin/users/delete', data)
export const listRemoteDevices = (data) => post('/remote-admin/devices/list', data)
export const updateRemoteDevice = (data) => post('/remote-admin/devices/update', data)
export const kickRemoteDevice = (data) => post('/remote-admin/devices/kick', data)
export const deleteRemoteDevice = (data) => post('/remote-admin/devices/delete', data)
export const listRemoteConnections = (data) => post('/remote-admin/connections/list', data)
export const deleteRemoteConnection = (data) => post('/remote-admin/connections/delete', data)
export const listRemoteCodeAttempts = (data) => post('/remote-admin/code-attempts/list', data)
export const deleteRemoteCodeAttempt = (data) => post('/remote-admin/code-attempts/delete', data)
export const listRemoteLegalDocuments = (data) => post('/remote-admin/legal-documents/list', data)
export const saveRemoteLegalDocument = (data) => post('/remote-admin/legal-documents/save', data)
export const deleteRemoteLegalDocument = (data) => post('/remote-admin/legal-documents/delete', data)
export const getRemoteAppFooter = (data) => post('/remote-admin/app-footer/get', data)
export const saveRemoteAppFooter = (data) => post('/remote-admin/app-footer/save', data)
export const listRemoteAppUpdates = (data) => post('/remote-admin/app-updates/list', data)
export const saveRemoteAppUpdate = (data) => post('/remote-admin/app-updates/save', data)
export const deleteRemoteAppUpdate = (data) => post('/remote-admin/app-updates/delete', data)
export const listRemoteLegalConsents = (data) => post('/remote-admin/legal-consents/list', data)
export const deleteRemoteLegalConsent = (data) => post('/remote-admin/legal-consents/delete', data)
export const listRemoteAccountDeletions = (data) => post('/remote-admin/account-deletions/list', data)
